# Generated by Django 5.1 on 2024-09-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='modifications',
            field=models.ManyToManyField(to='my_app.modification'),
        ),
    ]
